add call back feature for registering handlers
alsami/MediatR.Extensions.Autofac.DependencyInjection pull request #24
Opened 2023-07-04 19:31 UTC by marmeladhero

2023-07-05 06:50 UTC, alsami requested changes

2023-07-05 06:50 UTC, alsami commented on src/Directory.Build.props
> +    <FileVersion>11.0.1.0</FileVersion>
That would be a new feature so please raise the version to 11.1.0.

2023-07-05 06:50 UTC, alsami commented on src/MediatR.Extensions.Autofac.DependencyInjection/Builder/MediatRConfigurationBuilder.cs
> +            this.registrationScope, this.internalCustomRegistrationAction);
New line this parameter please.

2023-07-05 06:50 UTC, alsami commented on src/MediatR.Extensions.Autofac.DependencyInjection/Builder/MediatRConfigurationBuilder.cs
> +    public MediatRConfigurationBuilder WithOpenGenericHandlerTypeToRegisterCallback(Action<IRegistrationBuilder<object, ScanningActivatorData, DynamicRegistrationStyle>> openGenericHandlerTypeToRegis
Please add tests for the new functionality so that we may validate that a callback is actually executed.

2023-07-05 06:50 UTC, alsami commented on src/MediatR.Extensions.Autofac.DependencyInjection/MediatRConfiguration.cs
> +    public void OpenGenericTypesToRegisterCallback(IRegistrationBuilder<object, ScanningActivatorData, DynamicRegistrationStyle> registeredType)
Please make this internal as well.

2023-07-05 06:50 UTC, alsami commented
> I know it can be done better disappointed

I think it is good, thanks for the addition. A few minor things + tests and we should be good to go :)

2023-07-05 09:34 UTC, marmeladhero commented
Check

2023-07-07 06:20 UTC, alsami commented
Can you please squash your commits and add a nice commit message that describes the change. Thanks

2023-07-07 07:12 UTC, marmeladhero commented
Am I done this correct?

2023-07-07 09:49 UTC, alsami commented
You currently have six commits. You need to squash them into one commit.

2023-07-10 11:53 UTC, closed without merging